# Generated by Django 2.0 on 2017-12-16 16:14

import datetime
import django.contrib.postgres.fields.jsonb
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralRisk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('riskName', models.CharField(max_length=20)),
                ('attr', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='LandRisk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('riskName', models.CharField(choices=[('car', 'car'), ('house', 'house'), ('supermarket', 'supermarket'), ('prize', 'prize'), ('healthCare', 'healthCare')], default='house', max_length=20)),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('address', models.TextField(max_length=120)),
                ('zoneNumber', models.IntegerField(blank=True, default=None, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100000)])),
                ('space', models.IntegerField()),
                ('floorNumber', models.IntegerField(blank=True, default=None, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(200)])),
            ],
        ),
    ]
